### ISSUE TITLE
Upgrade failed : src_path : variable sans liaison

### ISSUE THREAD

**Issue by tomdereub** [YunoHost-Apps/collabora_ynh#23]
Full log : https://paste.yunohost.org/raw/ijezobotuv
Collabora is still working for me, I just can't upgrade. Thanks for the work!

**Comment by yalh76** [comment]
Can you try to upgrade to the last version and let us know if there is still an error

**Comment by tomdereub** [comment]
I have still an error, here is the full log : https://paste.yunohost.org/raw/exakarahiq

**Comment by yalh76** [comment]
Maybe you should remove collabora and reinstall it from sratch ^^

**Comment by tomdereub** [comment]
You're right, I reinstalled it and it's working very well, thank you !
