### ISSUE TITLE
Unauthorized WOPI host in Yuno Host Installation of Nextcloud and Collabora online

### ISSUE THREAD

**Issue by nukedone** [YunoHost-Apps/collabora_ynh#32]
This message presents although I tried to edit the settings in `/etc/loowsd/loowst.xml`. My nextcloud is located in the https://domain.tld/nextcloud. Collabora server has a separate domain https://collabora.domain.tld. BOth domains are provided with Let's Encrypt Certificates.

**Comment by wget** [comment]
Are you sure there is no missmatch in the config between the usual https connection and the websocket one?

Could you paste your config files?

**Comment by nukedone** [comment]
I solved the problem by

Inserting into `/etc/loolwsd/loolwsd.xml` value of the domain URL into a property at the beginning of the config file. I am not at the moment near my server so O will post the property name when I get there.

⁣Get BlueMail for Android ​

**Comment by wget** [comment]
@nukedone Great! When you find some time, don't hesitate to provide chat you changed :) This may help others fixing their issues if they find this issue :)

**Comment by ianalexis** [comment]
@nukedone the same is happening here, could you please share how did you add eht value on the XML?
Thanks
Rgrds.-

**Comment by nukedone** [comment]
I believe that the file is in `/etc/loolwsd/loolwsd.xml`. I have
forotten what property I changed but I believe that it is
`<server_name>`. However, it stopped working again. Now, I have the
latest Yunohost and the latest Collabora and things seem to work fine.
I didn't update Nextcloud to version 20.

**Comment by mo-kuh** [comment]
Hey, i encounter the same problem :(

"
Document loading failed

Unauthorized WOPI host. Please try again later and report to your administrator if the issue persists.
"

Strange thing is: I can use the collabora server (and others) from several other nextcloud instance but only the main one does not work with any of my own collabora servers.

Some system info:
Yunohost: 11.2.14.1 (stable)
Nextcloud: 28.0.6
Collabora: Collabora Online Development Edition 24.04.3.1 594b605

I am happy to provide more info. Couldnt find solutions anywhere :(
