### ISSUE TITLE
Attempting to load any file on Nextcloud fails

### ISSUE THREAD

**Issue by csolisr** [YunoHost-Apps/collabora_ynh#50]
### Describe the bug

When attempting to load any LibreOffice file on Nextcloud, the system consistently fails to load it with an error message

### Context

- Hardware: *Intel NUC*
- YunoHost version: 4.2.6.1
- I have access to my server: *Through SSH, webadmin, direct access*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain: Followed additional steps described in [this issue](https://github.com/YunoHost-Apps/collabora_ynh/issues/49), see below
- Using, or trying to install package version/branch: Collabora 6.4.10

### Steps to reproduce

- Install Nextcloud and the Collabora plugin
- Install Collabora, configure it to use Nextcloud's domain
- In the settings file at /etc/loolwsd/loolwsd.xml, configure `limit_virt_mem_mb`, `limit_stack_mem_kb`, `limit_file_size_mb`, `limit_load_seconds`, `limit_convert_seconds`, and `max_file_size` to 0 to prevent timeouts
- Configure Nextcloud via the Collabora plugin to connect to the server
- Open any LibreOffice file via Nextcloud (tested with ODS and ODT files)

### Expected behavior

The file should load after a certain amount of time, but it never does. Instead, a popup appears with the following message:

> Failed to load the document. This document is either malformed or is taking more resources than allowed. Please contact the administrator.

### Logs

Relevant lines from `journalctl -u loolwsd`, just as a file is attempting to load:
```
DBG  Inserting socket #16 into kit| ./net/Socket.hpp:697
DBG  #16 Thread affinity set to 0 (was 0x7f9d8fced7c0).| ./net/Socket.hpp:308
TRC  #16: Set socket buffer size to 262144| ./net/Socket.hpp:229
INF  New kit client websocket inserted.| kit/Kit.cpp:2673
INF  Kit initialization complete: setting log-level to [warning] as configured.| kit/Kit.cpp:2678
WRN  link("/tmp/convert-to/tmp29852baaaaa/#2#bf198607528ceecf#", "/opt/lool/child-roots/uAmL3OQkhZhrwOi0/tmp/user/docs/uAmL3OQkhZhrwOi0/#2#bf198607528ceecf#") failed. Will copy. Linking error: EXDEV Cross-device link not permitted| wsd/Storage.cpp:370
WRN  getNewChild: No child available. Sending spawn request to forkit and failing.| wsd/LOOLWSD.cpp:609
WRN  link("/tmp/convert-to/tmp29852caaaaa/#2#bf198607528ceecf#", "/opt/lool/child-roots/JQ201vJwwCm3mD2f/tmp/user/docs/JQ201vJwwCm3mD2f/#2#bf198607528ceecf#") failed. Will copy. Linking error: EXDEV Cross-device link not permitted| wsd/Storage.cpp:370
WRN  Waking up dead poll thread [HttpSynReqPoll], started: false, finished: false| ./net/Socket.hpp:682
ERR  Exception while loading url [file:///tmp/user/docs/GFiEdUYiLYv3q70l/6073920_oc3r8y6dwots.ods] for session [009]: Invalid or unsupported charset:us-ascii or UTF-8| kit/Kit.cpp:1011
ERR  Failed to get LoKitDocument instance for [file:///tmp/user/docs/GFiEdUYiLYv3q70l/6073920_oc3r8y6dwots.ods].| kit/ChildSession.cpp:684
ERR  #27: Socket write returned -1 (EPIPE: Broken pipe)| ./net/Socket.hpp:1280
WRN  client - server version mismatch, disabling browser cache. Expected: 2afbc52| wsd/FileServer.cpp:288
ERR  FileServerRequestHandler::NotAuthenticated: No authentication information found| wsd/FileServer.cpp:479
WRN  client - server version mismatch, disabling browser cache. Expected: 2afbc52| wsd/FileServer.cpp:288
WRN  Ignoring attempted read from 20| ./net/Socket.hpp:1017
WRN  client - server version mismatch, disabling browser cache. Expected: 2afbc52| wsd/FileServer.cpp:288
```

**Comment by mateMathieu** [comment]
Same thing here.
Also use a similar configuration you describe in the Bug #49.
The office.example.com is the collabora and the mextcloud.example.com is the nextcloud.
Let me know if you need additional info.

Best

**Comment by timar** [comment]
Out of interest, what is your language setting in Nextcloud?

**Comment by csolisr** [comment]
Spanish (Latin America) - I'll try setting it to English to see if it changes anything

**Comment by timar** [comment]
@csolisr Thank you. See also https://github.com/nextcloud/richdocuments/pull/2054
The fix in LOKit will follow soon.
