### ISSUE TITLE
Dictionaries

### ISSUE THREAD

**Issue by coolkau** [YunoHost-Apps/collabora_ynh#61]
When installing via Yunohost, no dictionaries will be installed/activated. I saw no option to set them, no mention in any of the docs. 
Is there anywhere a place to pass options to the installer? I might miss something obvious, as I dont think I'd be the first one to ask this.

**Comment by Sonnenblumenkind** [comment]
You have to install hunspell:

```
sudo apt install hunspell
systemctl restart coolwsd
```

Wait a few moments and it should work
If you want to add dictionaries:
```
sudo apt install hunspell-en-gb
sudo apt install hunspell-de-de
```
etc.

Do a:
`systemctl restart coolwsd`
each time you have installed a new dictionary
