### ISSUE TITLE
Update from 21.11.0.6~ynh1 to 21.11.4.1~ynh1 makes Collabora unusable.

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/collabora_ynh#63]
### Describe the bug

Update from 21.11.0.6~ynh1 to 21.11.4.1~ynh1 makes Collabora unusable.

### Context

Hardware: Old laptop or computer
YunoHost version: 4.3.6.3
I have access to my server : Through SSH | through the webadmin | direct access via keyboard / screen | …
Are you in a special context or did you perform some particular tweaking on your YunoHost instance ? : no

### Steps to reproduce

After update, nextcloud became very slow and nextcloud could not connect anymore to collabora serveur. Deactivating the Collabora online app in Nextcloud made nextcloud fast again.

### Expected behavior

Keep working as usual or better after update :-)

### Logs

logs of collabora update : https://paste.yunohost.org/raw/xotariyofa

**Comment by Thatoo** [comment]
I enabled again the collabora app in nextcloud but remove the link to the server and it keep being fast so the problem is not the app but the link between nextcloud and collabora serveur.

**Comment by Thatoo** [comment]
If `https://office.domain.tld` tells me 

> This is where Collabora Online is installed. To actually be useful, this needs to be integrated in a front-end such as Nextcloud for example.

`https://office.domain.tld/browser/dist/admin/admin.html` gives me a 504 Gateway Time-out page

**Comment by Thovi98** [comment]
Mmh I think I’ve had the same issue so I’ve reinstalled the app and now it works great

**Comment by Thatoo** [comment]
Indeed, it worked. Thank you!
