### ISSUE TITLE
Admin interface is blank

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/collabora_ynh#8]
Hello,
When I try to connect to `https://your_domain.com/loleaflet/dist/admin/admin.html`, the result is a blank page.

In Nextcloud, I have a grey area instead of collabora UI.

How can I solve this ?

edit: If I look into the console window, the admin.html line seems to show a 404 error.

**Comment by yalh76** [comment]
Can you try with the last version of collabora and let us know if there is still an error
